{
 "title": "Federated IAM User Cost",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Account_ID",
    "label": "Account ID",
    "query": {
     "query": "label_values(FED_USER_Resource_Cost_List,account_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cost of all the Federated IAM User",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(account_id) (FED_USER_Resource_Cost_List{account_id=~\"$Account_ID\"})",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  {
   "title": "Cost Split in AWS Services",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(resource) (sum without(region, resource_id, resource_name) (FED_USER_Resource_Cost_List{account_id=~\"$Account_ID\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Spent on Federated IAM Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FED_USER_Resource_Cost_List{account_id=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}